# Generated by Django 5.2.5 on 2025-09-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('velg', 'Velg'), ('body', 'Body'), ('lampu', 'Lampu')], default='velg', max_length=50),
        ),
    ]
