# Generated by Django 5.2.5 on 2025-09-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('velg', 'Velg'), ('karbu', 'Karbu'), ('lampu', 'Lampu'), ('blocksilinder', 'Blocksilinder'), ('headsilinder', 'Headsilinder'), ('krukas', 'Krukas'), ('shock', 'Shock')], default='', max_length=50),
        ),
    ]
